function [fitresult, gof] = createFit(kracht_terug, gemeten_spanning_terug)
%CREATEFIT(KRACHT_TERUG,GEMETEN_SPANNING_TERUG)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : kracht_terug
%      Y Output: gemeten_spanning_terug
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 10-Jan-2018 12:24:13


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( kracht_terug, gemeten_spanning_terug );

% Set up fittype and options.
ft = fittype( 'poly3' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'gemeten_spanning_terug vs. kracht_terug', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel kracht_terug
ylabel gemeten_spanning_terug
grid on


