function [fitresult, gof] = createFit(kracht_terug, gemeten_spanning_terug, wieghts_terug)
%CREATEFIT(KRACHT_TERUG,GEMETEN_SPANNING_TERUG,WIEGHTS_TERUG)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : kracht_terug
%      Y Output: gemeten_spanning_terug
%      Weights : wieghts_terug
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Jan-2018 10:42:01


%% Fit: 'untitled fit 1'.
[xData, yData, weights] = prepareCurveData( kracht_terug, gemeten_spanning_terug, wieghts_terug );

% Set up fittype and options.
ft = fittype( 'poly1' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'gemeten_spanning_terug vs. kracht_terug with wieghts_terug', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel kracht_terug
ylabel gemeten_spanning_terug
grid on


