function [fitresult, gof] = createFit(kracht_heen, gemeten_spanning_heen, wieghts_heen)
%CREATEFIT(KRACHT_HEEN,GEMETEN_SPANNING_HEEN,WIEGHTS_HEEN)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : kracht_heen
%      Y Output: gemeten_spanning_heen
%      Weights : wieghts_heen
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Jan-2018 10:29:48


%% Fit: 'untitled fit 1'.
[xData, yData, weights] = prepareCurveData( kracht_heen, gemeten_spanning_heen, wieghts_heen );

% Set up fittype and options.
ft = fittype( 'poly1' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'gemeten_spanning_heen vs. kracht_heen with wieghts_heen', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel kracht_heen
ylabel gemeten_spanning_heen
grid on


