function [fitresult, gof] = createFit(massa, spanning_piek1)
%CREATEFIT(MASSA,SPANNING_PIEK1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : massa
%      Y Output: spanning_piek1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Jan-2018 21:53:18


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( massa, spanning_piek1 );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
% Label axes
xlabel massa
ylabel spanning_piek1
grid on


