function [fitresult, gof] = createFit(kracht, spanning_piek1)
%CREATEFIT(KRACHT,SPANNING_PIEK1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : kracht
%      Y Output: spanning_piek1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 10-Jan-2018 17:11:07


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( kracht, spanning_piek1 );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'spanning_piek1 vs. kracht', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel kracht
ylabel spanning_piek1
grid on


