function [fitresult, gof] = createFit(massa, spanning_piek2)
%CREATEFIT(MASSA,SPANNING_PIEK2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : massa
%      Y Output: spanning_piek2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Jan-2018 21:53:36


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( massa, spanning_piek2 );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'spanning_piek2 vs. massa', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel massa
ylabel spanning_piek2
grid on


