function [fitresult, gof] = createFit(kracht, spanning_piek2)
%CREATEFIT(KRACHT,SPANNING_PIEK2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : kracht
%      Y Output: spanning_piek2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-Jan-2018 13:44:57


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( kracht, spanning_piek2 );

% Set up fittype and options.
ft = fittype( 'a*x+b', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.186872604554379 0.489764395788231];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'spanning_piek2 vs. kracht', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel kracht
ylabel spanning_piek2
grid on


